# Simple Cloud Build configuration
steps:
  # Build and push backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/boxwood-scope-463317-b6/rap-battle-backend', '-f', 'backend/Dockerfile', 'backend']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/boxwood-scope-463317-b6/rap-battle-backend']
    
  # Build and push frontend  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/boxwood-scope-463317-b6/rap-battle-frontend', '-f', 'frontend/Dockerfile', 'frontend']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/boxwood-scope-463317-b6/rap-battle-frontend']
    
  # Deploy backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'rap-battle-backend'
      - '--image=gcr.io/boxwood-scope-463317-b6/rap-battle-backend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8456'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=100'
      - '--concurrency=1000'
      - '--timeout=3600'
      - '--session-affinity'
      - '--no-cpu-throttling'
      - '--set-env-vars=NODE_ENV=production,GOOGLE_CLOUD_PROJECT_ID=boxwood-scope-463317-b6,TTS_LANGUAGE_CODE=ja-JP,TTS_VOICE_NAME=ja-JP-Wavenet-A,ALLOWED_ORIGINS=https://rap-battle-frontend-bslarjwwyq-uc.a.run.app'
      - '--update-secrets=GEMINI_API_KEY=gemini-api-key:1'
      
  # Get backend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-backend-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe rap-battle-backend --region=us-central1 --format='value(status.url)')
        echo $BACKEND_URL > /workspace/backend-url.txt
        
  # Deploy frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend-url.txt)
        gcloud run deploy rap-battle-frontend \
          --image=gcr.io/boxwood-scope-463317-b6/rap-battle-frontend \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=3456 \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=50 \
          --concurrency=1000 \
          --set-env-vars="NODE_ENV=production,NEXT_PUBLIC_API_URL=$BACKEND_URL,NEXT_PUBLIC_WEBSOCKET_URL=$BACKEND_URL"

timeout: '1800s'